### ISSUE TITLE
Sections don't load for pages?sectionName snippet

### ISSUE THREAD

**Issue by DianeD** [OneNoteDev/Android-REST-API-Explorer#51]

**Comment by iambmelt** [comment]
Thanks for finding this issue!

It appears per [this doc](http://dev.onenote.com/docs#/reference/get-sections) that the ```com.microsoft.onenotevos.Section```'s field ```parentSectionGroup``` should be ```com.microsoft.onenotevos.SectionGroup``` instead of ```java.lang.String```
